### ISSUE TITLE
Custom styles: Plain, Image and inner Div are not processed

### ISSUE THREAD

**Issue by glassdimly** [jzeneto/pandoc-odt-filters#1] opened 2018-07-23 14:44 UTC
Hey @jzeneto,

Thanks for the filters. I'm still wrapping my head around the `lua` syntax and what's being done in `odt-custom-styles.lua`, but I think I'll be able to contribute back once I do.

So, the custom styles are not being created for me. 

Here's my command:
`pandoc Thinspace.html  --lua-filter ./pandoc-odt-filters/odt-custom-styles.lua  -o thinspace-pandoc3.odt`

I have markup that looks like this:
`<div custom-style="scene-sep" class="scene-sep" style="text-align: center;">* * * * *</div>`

It is styled on output in `odt` as `Text body`, and there is no custom style created called `scene-sep` as expected.

I'll dive into this in the evening, but any leads as to why this is not working? 

Also, I have full control over input markup. (I wrote a bunch of gulp plugins to coerce my `md` files into the output html structure.)

**Comment by josineto** [comment] 2018-07-23 17:18
Thanks for using them, @glassdimly!

Any custom style that's not defined at reference document (kind of template in odt/docx) will open as default style (in that case, `Text body`). But the style probably **is** at the text, LibreOffice just doesn't know it. To check this, decompress the odt file (it's just a zip file), open `content.xml`and search for `scene-sep`. If it's there, the problem is lack of style on reference doc.

To accomplish this, add to your command: `--reference-doc=your-styled-doc.odt`, where `your-styled-doc.odt`is an odt where `scene-sep` style (and any others) is defined.

(You can use a document with text, for instance an already done document. Pandoc will grab just the styles, not the content.)

**Comment by glassdimly** [comment] 2018-07-24 04:05
Thanks for your response.

Nope, definitely nothing is being set.

Output in `content.xml`:
`<text:p text:style-name="Text_20_body">* * * * *</text:p>`

In fact, when I generate an `rst`, I see none of the raw opendoc stuff I'd expect, even after changing the following line ` if (FORMAT == 'odt' or FORMAT == 'docx'  or FORMAT == 'rst') then` and using this command:

`pandoc Thinspace.html --reference-doc ~/.pandoc/ms-format.odt --lua-filter ./pandoc-odt-filters/odt-custom-styles.lua  -o thinspace-pandoc3.rst`

Additionally, I have created the style `scene-sep` in my reference doc, and I can see it in the output doc, but it is not applying to the scene separators.

Is it possible the filter is not running? I have the repo checked out at `pandoc-odt-filters`. Any suggestions here?

**Comment by josineto** [comment] 2018-07-24 16:38
The paragraph in question is an Horizontal Rule (`<hr/>` in HTML)? If this is the case, the filter doesn't process them. I'm working on this.

About raw opendoc stuff not appearing in rst conversion, it's expected. I use `RawBlock`s and `RawInlines` to do the processing, and these pandoc elements receive a `type` argument (in odt case, `opendocument`). So, these elements are processed only at the correct type; in all others, they are ignored (see [Pandoc manual on this](https://pandoc.org/MANUAL.html#generic-raw-attribute)).

**Comment by josineto** [comment] 2018-07-24 17:10
I've corrected this on `odt-custom-styles.lua`, and changed README accordingly. @glassdimly please test if that change works for you.

**Comment by glassdimly** [comment] 2018-07-29 19:49
@jzeneto,

The paragraph in question is/was not a `hr`. The markup is like so:
` <div custom-style="scene-sep" class="scene-sep" style="text-align: center;">* * * * *</div>`

I'm having another pass at this so I'll update this thread.

**Comment by glassdimly** [comment] 2018-07-29 22:17
Alright, I just can't get this to work at all. Lua is kind of a pain because it doesn't properly log errors or output anywhere.

I'm going to post my files so you can help troubleshoot, if that's of interest to you.

Again, thanks for you help--it's clear you put a lot of work into this plugin.

[pandoc-troubleshooting.zip](https://github.com/jzeneto/pandoc-odt-filters/files/2239239/pandoc-troubleshooting.zip)

My command: 

`pandoc Thinspace.html --reference-doc custom-reference.odt --lua-filter pandoc-odt-filters/odt-custom-styles.lua  -o thinspace.odt  --log=log.log`

There should be at least two custom styles imported, `scenesep` and `qr-img`, and while those styles do exist in the output odt doc, the text does not get styled.

I'm going to keep working on this until I get custom styles outputted.

**Comment by glassdimly** [comment] 2018-07-29 22:38
Hey, I figured this out. Your code requires a nested element.

Doesn't work:
`<div class="scenesep" custom-style="scenesep">* * * * *</div>`

Works:
`<div class="scenesep" custom-style="scenesep"><p>* * * * *</p></div>`

It's because of this:

`div = pandoc.walk_block(div, getFilter(customStyle))`

**Comment by glassdimly** [comment] 2018-07-29 23:17
Yeah, I thought this was working. I saw the output. But I can't replicate it. I have no idea why.

**Comment by josineto** [comment] 2018-07-30 03:37
Ok, I've debugged a while with your files, and here's the problem: Pandoc uses `Plain` element with any div content not nested in a paragraph tag. As `odt-custom-styles.lua` has ignored `Plain` elements, your div contents were ignored, and styling was by-passed (I wrote the filter using only markdown -> odt conversion, and `Plain` is used in markdown only in list items and table cells, which falls out of the filter scope). Also, you put the styles as div classes, and the filter didn't use classes.

The `Plain` elements are converted to `Para`s (paragraph elements) by Pandoc, so I made the filter process `Plain`, using the same rules of `Para`. This worked fine for the first (asterisks) and third (link) div, but the second one, a figure, is not parsed because, as the filter description says, figures/images are not currently supported.

I'll commit this change, but you'll have to remove the class of the div with image (`qr-wrapper` class) for the change work properly. And, for the class/custom-style problem, I put a local variable, `useClassAsCustomStyle` (default `true`) at the beginning of filter, that turns first class of element into custom-style if no `custom-style` attribute is set --- just for div's, spans and headers, of course. I turned this configurable because use of `class` as `custom-style` is currently under discussion (see jgm/pandoc#2106).

**Comment by glassdimly** [comment] 2018-07-30 03:54
Thank you, @jzeneto!

I can wrangle my markup into whatever format is required.

**Comment by glassdimly** [comment] 2018-07-30 04:07
Well, I'm making some progress on seeing what lua is doing! https://github.com/kikito/inspect.lua

If what you said about `Plain` were true then this element would render fine (it is a `div` nested in a `p` and thus would be rendered as `Div`):

`  <p><div class="scenesep" custom-style="scenesep"><p>* * * * *</p></div></p>`

But instead I get this:

`<text:p text:style-name="Text_20_body">* * * * *</text:p>`

**Comment by josineto** [comment] 2018-07-30 04:13
Sorry, but that code is not *semantic*: it's a paragraph (block element) with a division inside (another block element), with a paragraph inside (another block element). Pandoc's `Para` doesn't support block elements inside of it; it's in fact the opposite way that is supported: `Para` *inside* `Div`.

The commit I've made was tested against files in the zip you uploaded (and against test files of this repository), and I found only the image-problem. Can you use the syntax of files in that zip? That is:

```html
<div class="scenesep">* * * * *</div>
```

If you want a division inside a paragraph, consider `<span>`. It's more semantic than `<div>` in this case.

**Comment by glassdimly** [comment] 2018-07-30 04:15
Alright, so to explain the confusion from before: it would seem that the following markup is/was working even before your commit:

`<p><div class="scenesep" custom-style="scenesep"><p>* * * * *</p></div></p>`

The reason why I got a false positive earlier was because I had an opening `<p>` tag that never got closed.

That is to say, what is working is: `p -> div -> p`, and the innermost `p` tag was the styles.

**Comment by glassdimly** [comment] 2018-07-30 04:17
Also, using the lua inspect library made debugging much easier: https://github.com/kikito/inspect.lua

**Comment by josineto** [comment] 2018-07-30 04:24
Thanks for the tip, I'll look for using that lib! The paragraphs got styled?

**Comment by josineto** [comment] 2018-07-30 04:48
As `Image`s can't be supported by the filter (see below), if you confirm that first and third divs of your files get styled, I'll close this issue, ok?

Why the filter can't process `Image`s?

Well, the only way I found to make custom styles work was turning all inner elements of a styled block into pure ODT code (but wrapped by `Str` elements), getting all this inner content as a string (with [`pandoc.utils.stringify()`](https://pandoc.org/lua-filters.html#utils-stringify)) and then turning the whole block into a [`RawBlock`](https://pandoc.org/lua-filters.html#RawBlock) with `format` equal to `opendocument`, and `text` equal to that string.

This works (relatively) fine for markup that can be printed by `pandoc.utils.stringify()`. But `Image`s, obviously, cannot. I can create the ODT code as a string, and put the path of the image in the code, but this would generate an ODT with the image *not* embedded, which is very fragile if you (or other users) don't use a consistent workflow.

To better understand why inner elements are processed before outer elements, remember the [Lua filter run order](https://pandoc.org/lua-filters.html#replacing-placeholders-with-their-metadata-value): 

> Inlines → Blocks → Meta → Pandoc.

**Comment by glassdimly** [comment] 2018-07-31 03:10
My divs are styled with your commit, and plain divs like so work fine:

`<div class="scenesep" custom-style="scenesep">* * * * *</div>`

On the matter of images, I understand the problem. I'm going to think on it.

**Comment by josineto** [comment] 2018-07-31 14:54
Good!! Sorry if I was a little unpolite before, my English is not so good.

I hope that custom styles gonna work natively with Pandoc soon.

**Closed as completed by josineto** 2018-07-31 14:54 UTC

**Comment by josineto** [comment] 2018-07-31 15:00
Just one more thing: with the commits, you don't have to especify `custom-style` attribute in div, just `class` (unless you want that `custom-style` be different from `class`; the former takes precedence with the filter). For this, keep the corresponding variable in filter equals `true` (I think it's `useClassAsCustomStyle`, but forgot the exact name).

**Comment by glassdimly** [comment] 2018-07-31 16:46
No worries. Yeah, the HTML was unsemantic, I was just posting to show it was working.

**Comment by glassdimly** [comment] 2018-08-02 02:51
Whelp. I figured out how to wrap my images in custom styles.

It's a little unrelated, but I wanted to report back.

First I tried the [php pandoc filters](https://github.com/jgm/pandoc/wiki/pandoc-Filters), because I mostly code in PHP. But the filter was sloooow, taking hours, so I aborted.

Then I used [node-pandoc-filters](https://www.npmjs.com/package/pandoc-filter), which took seconds. First I base64ed my images with gulp. Then, I [stripped the preceding formatting](https://stackoverflow.com/questions/51618563/what-base64-format-to-use-for-images-in-opendocument-odt-officebinary-data-p) and used the `<office:binary-data>` tag, then made the following script, executed with the `--filter styles.js` option:
```
#!/usr/bin/env node

var pandoc = require('pandoc-filter');

function action(type,value,format,meta) {

  if (type === 'Para') {
    if (value[0] !== undefined && value[0].hasOwnProperty('t') && value[0].t === 'Image'
      && value[0].hasOwnProperty('c') && value[0].c[2] !== undefined && value[0].c[2][0] !== undefined && typeof value[0].c[2][0] === 'string'
    ) {
      var src = value[0].c[2][0].replace('data:image/png;base64,', '');
      if (src) {
        return pandoc.RawBlock('opendocument', `<text:p text:style-name="qr-wrapper"><draw:frame draw:name="img1" svg:width="150.0pt" svg:height="150.0pt"><draw:image xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad">
          <office:binary-data>
          ${src}
          </office:binary-data></draw:image></draw:frame></text:p>`);
      }

    }
  }
}

pandoc.stdio(action);
```

Yeah, obviously not something that can be contributed back.
